### ISSUE TITLE
libstomp link is dead

### ISSUE THREAD

**Issue by ullgren** [stomp/stomp.github.com#26]
On the [Implementations](http://stomp.github.io/implementations.html) page the [link to libstomp](http://stomp.codehaus.org/C) is broken. Even googling fails to find anything that looks like the new official home of libstomp.

**Comment by LionelCons** [comment]
Fixed in https://github.com/stomp/stomp.github.com/commit/7052d5cf4c8886d344fc597b1b742f695c1d63b0. Thanks!
